version: '3.7'
services:
  nginx:
    container_name: xperta_prod_web
    restart: on-failure
    image: nginx:1.19.8
    volumes:
      - ./nginx/prod/nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/staticfiles
    ports:
      - 5000:80
    depends_on:
      - web
  web:
    container_name: xperta_prod_backend
    build:
      context: .
      dockerfile: Dockerfile.prod
    restart: always
    volumes:
      - static_volume:/app/staticfiles
    env_file:
      - ./website/.prod.env

volumes:
  static_volume: