version: '3.7'
services:
  web:
    container_name: xperta_dev_backend
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8000:8000
    env_file:
      - ./website/.env