version: '3.7'
services:
  web:
    container_name: xperta_dev_backend
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8000:8000
    volumes:
      - ./website/:/app/
    env_file:
      - .env.dev